name: Validate pecl package

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  test_package_valid:
    name: basic PHP ${{ matrix.php }}
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 5.6 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Sanity check package.xml and install ImageMagick
        run: |
          bash validate_package.sh
          for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done



