name: Build and Test on Windows
on: [push]
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        version: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
        arch: [x64]
        ts: [ts]
        exclude:
          - {os: windows-2019, version: "8.4"}
          - {os: windows-2019, version: "8.3"}
          - {os: windows-2019, version: "8.2"}
          - {os: windows-2019, version: "8.1"}
          - {os: windows-2019, version: "8.0"}
          - {os: windows-2022, version: "7.4"}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout imagick
        uses: actions/checkout@v4
      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@v0.10
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
          cache: true
      - name: Download deps
        run: |
          curl -LO https://downloads.php.net/~windows/pecl/deps/ImageMagick-7.1.0-18-vc15-${{matrix.arch}}.zip
          7z x ImageMagick-7.1.0-18-vc15-${{matrix.arch}}.zip -o..\deps
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: phpize
      - name: configure
        run: configure --with-imagick --with-php-build=..\deps --with-prefix=${{steps.setup-php.outputs.prefix}}
      - name: make
        run: nmake
      - name: test
        run: nmake test TESTS="-j4 --show-diff -g FAIL,BORK,WARN,LEAK tests"
