name: Build and Test on Windows
on: [push]
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          version: ["8.3"]
          arch: [x64]
          ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Checkout imagick
        uses: actions/checkout@v4
      - name: Extract Version
        shell: powershell
        run: |
          chcp 65001
          $r = Select-String -Path package.xml -Pattern '<release>([\d\.]+)</release>'
          $s = $r.Matches[0].Groups[1]
          $extension_version = 'EXTENSION_VERSION=' + $s
          echo $extension_version >> $env:GITHUB_ENV
          echo $extension_version
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.8
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Download deps
        run: |
          curl -LO https://windows.php.net/downloads/pecl/deps/ImageMagick-7.1.0-18-vc15-${{matrix.arch}}.zip
          7z x ImageMagick-7.1.0-18-vc15-${{matrix.arch}}.zip -o..\deps
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: phpize
      - name: configure
        run: configure --with-imagick --with-php-build=..\deps --with-prefix=${{steps.setup-php.outputs.prefix}}
      - name: make
        run: nmake
      - name: test
        run: nmake test TESTS="-j4 --show-diff -g FAIL,BORK,WARN,LEAK tests"
      - name: Define Module Env
        shell: powershell
        run: |
          chcp 65001

          $dir = (Get-Location).Path + '\'
          if ('x64' -eq '${{matrix.arch}}') { $dir = $dir + 'x64\' }
          $dir = $dir + 'Release'
          if ('ts' -eq '${{matrix.ts}}') { $dir = $dir + '_TS' }

          $artifact_name = 'php_imagick-${{env.EXTENSION_VERSION}}-${{matrix.version}}'

          if ('8.0' -eq '${{matrix.version}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.1' -eq '${{matrix.version}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.2' -eq '${{matrix.version}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.3' -eq '${{matrix.version}}') { $artifact_name = $artifact_name + '-vs16' }

          if ('nts' -eq '${{matrix.ts}}') { $artifact_name = $artifact_name + '-nts' }
          if ('x64' -eq '${{matrix.arch}}') { $artifact_name = $artifact_name + '-x86_64' }

          $extension_artifact_name = "ARTIFACT_NAME=" + $artifact_name
          echo $extension_artifact_name >> $env:GITHUB_ENV
          echo $extension_artifact_name

          $from = $dir + '\php_imagick.dll'
          $to = $from + ".zip"
          Compress-Archive $from $to
          $extension_artifact = "ARTIFACT=" + $from
          echo $extension_artifact >> $env:GITHUB_ENV
          echo $extension_artifact

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{env.ARTIFACT_NAME}}
            path: ${{env.ARTIFACT}}
      - name: Publish Binaries to Release
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: svenstaro/upload-release-action@v2
        with:
            asset_name: ${{env.ARTIFACT_NAME}}.zip
            file: ${{env.ARTIFACT}}.zip
